services:
  roster-to-ical:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: roster-to-ical
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
      - ./downloads:/app/downloads
      - ./processed_rosters.json:/app/processed_rosters.json
      - ./schedule.ics:/app/schedule.ics
    environment:
      - PYTHONUNBUFFERED=1

  vrr-monitor:
    build:
      context: ./vrr-monitor
      dockerfile: Dockerfile
    container_name: vrr-monitor
    restart: always
    ports:
      - "3000:3000"

